### ISSUE TITLE
ENOENT error at "variables" step (Windows)

### ISSUE THREAD

**Issue by batjko** [workshopper/learn-sass#43]
Hi there, 
I'm getting this error when I try to verify the very first exercise:

Solution:

``` sass
$color: #000;

body {
  color: $color;
}
```

Error:

``` bash
PS C:\git\learn-sass> learn-sass verify app.scss
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\pmetz\AppData\Roaming\npm\node_modules\learn-sass\node_modules\node-sass\bin\node-sass ENOENT
    at exports._errnoException (util.js:1007:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

As you can see, this is on Windows. I've tried saving the file with *nix line endings instead, but still the same.

**EDIT:**
Note, I have installed learn-sass on the bash subsystem of Windows. It works fine there, so this is evidently an issue on Windows shells only.

**Comment by dloret** [comment]
Hello, I'm on Windows 10 and having the same issue on the "Variables" and "Nesting" exercises. Looks like I can't use your wonderful learning resource on windows. That's a waste:
`aside {
    ul {
        margin: 0;
    }
    a {
        color: red;
    }
}`

`PS C:\Users\I079276\Desktop> learn-sass verify ss.scss
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\I079276\AppData\Roaming\nvm\v7.0.0\node_modules\learn-sass\node_modules\node-sass\bin\node-sass ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by fega** [comment]
I'm having a similar error. :/

learn-sass verify style.scss
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\Fabian Gutierrez\AppData\Roaming\npm\node_modules\learn-sass\node_modules\node-sass\bin\node-sass ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by opperbolt** [comment]
same here on win10
also nodeschool links to https://github.com/claudiopro/learn-sass instead of this repository

**Comment by claudiopro** [comment]
Issue looks similar to [this StackOverflow post](http://stackoverflow.com/questions/37459717/error-spawn-enoent-on-windows#37487465).

**Comment by claudiopro** [comment]
Nice explanation of the issue in this doc page: https://nodejs.org/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows

I'll switch to [cross-spawn](https://www.npmjs.com/package/cross-spawn#why) though, as it's a better fix that works in Node <6 too.

**Comment by batjko** [comment]
I'm on Node 6.9.4.
