### ISSUE TITLE
Exit from application

### ISSUE THREAD

**Issue by LightTest** [workshopper/learn-sass#62]
After install I do have your windows as in your example but after choosing lesson, I do have short info about syntax and the program breaks, to choose new lesson there is a need to restart the program.

I don't know if it's normal but if yes there is no issue. Anyway I can't have your message completed ;(.

**Comment by LightTest** [comment]
I run a command learn-sass verify stylesheet.scss but I have an error :  events.js:160 throw er;

**Comment by claudiopro** [comment]
Hi @LightTest, the program terminates after choosing a lesson. This behavior is expected. You have to run `learn-sass verify solution.scss` to verify it 😄 

Can you provide more details on the version of operating system, node, and npm you're using?

Please type these commands in a shell and reply with the output:

```
node --version
npm --version
```

**Comment by mahopa** [comment]
Same issue. Verify fails. 

Works on my mac fails on windows. Appears to be coming from the node-sass module.

Tried on multiple node versions windows:
node v.6.11.1
npm 3.7.5

node v8.9.4
npm 3.7.5

Error below:

$ learn-sass verify test.scss
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\alex.miller\AppData\Roaming\npm\node_modules\learn-sass\node_modules\node-sass\bin\node-sass ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by TPXP** [comment]
I confirm the bug. I'm using ArchLinux with Node `v9.4.0`. `node-sass` is installed in the same folder as `learn-sass` whereas the workshop expects it to be in a subdirectory of its directory.

**Comment by claudiopro** [comment]
Unfortunately I don't have a Windows system to troubleshoot the issue and would have to spin up a VM. If someone can take a look it would be great! 🎉

I'll tag this as help needed.

**Comment by TPXP** [comment]
The bug also occurs on Linux. It happens if you don't use the `-g` flag for installing the workshop.

See #65 for a fix
