### ISSUE TITLE
Unable to Install learn-sass

### ISSUE THREAD

**Issue by SB1lal** [workshopper/learn-sass#70]
```
D:\NodeSchool>npm install -g learn-sass
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated colors-tmpl@1.0.0: no longer maintained
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\bilal\\AppData\\Roaming\\npm\\node_modules\\learn-sass\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\bilal\AppData\Roaming\npm\node_modules\learn-sass\node_modules\node-sass\src\libsass'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\bilal\\AppData\\Roaming\\npm\\node_modules\\learn-sass\\node_modules\\node-sass\\src\\libsass'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\bilal\\AppData\\Roaming\\npm\\node_modules\\learn-sass',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\bilal\AppData\Roaming\npm\node_modules\learn-sass\node_modules\node-gyp'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\bilal\\AppData\\Roaming\\npm\\node_modules\\learn-sass\\node_modules\\node-gyp'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\bilal\AppData\Roaming\npm\node_modules\learn-sass\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\bilal\AppData\Roaming\npm\node_modules\learn-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\bilal\\AppData\\Roaming\\npm\\node_modules\\learn-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@20.11.1 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\bilal\AppData\Roaming\npm\node_modules\learn-sass\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\bilal\AppData\Roaming\npm\node_modules\learn-sass\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\bilal\AppData\Roaming\npm\node_modules\learn-sass\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\bilal\AppData\Roaming\npm\node_modules\learn-sass\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\bilal\AppData\Roaming\npm\node_modules\learn-sass\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\bilal\AppData\Roaming\npm\node_modules\learn-sass\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:201:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\bilal\AppData\Roaming\npm\node_modules\learn-sass\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\bilal\AppData\Roaming\npm\node_modules\learn-sass\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\bilal\AppData\Roaming\npm\node_modules\learn-sass\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\bilal\AppData\Roaming\npm\node_modules\learn-sass\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\bilal\AppData\Roaming\npm\node_modules\learn-sass\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\bilal\AppData\Roaming\npm\node_modules\learn-sass\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:201:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Users\bilal\AppData\Local\Programs\Python\Python312\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Users\bilal\AppData\Local\Programs\Python\Python312\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:422:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm ERR! gyp ERR! System Windows_NT 10.0.22631
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\bilal\\AppData\\Roaming\\npm\\node_modules\\learn-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\bilal\AppData\Roaming\npm\node_modules\learn-sass\node_modules\node-sass
npm ERR! gyp ERR! node -v v20.11.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in: C:\Users\bilal\AppData\Local\npm-cache\_logs\2024-04-22T11_24_57_976Z-debug-0.log
```

**Comment by leonaaaardo** [comment]
https://www.npmjs.com/package/windows-build-tools
